<?php
namespace Conekta;
use \Conekta\Conekta;
use \Conekta\Exceptions;
use \Exception;

class ProcessingError extends Handler
{
    public function getConektaMessage()
    {
        return parent::getConektaMessage(); // TODO: Change the autogenerated stub
    }
}
